In [4]:
import numpy as np
array = np.array([[1,2,3],[2,3,4]])
print(array)

[[1 2 3]
 [2 3 4]]


In [5]:
print('number of dim:',array.ndim)
print('shape:',array.shape)
print('size',array.size)

number of dim: 2
shape: (2, 3)
size 6


In [9]:
a = np.array([2,23,4])
print(a)

[ 2 23  4]


In [10]:
a = np.array([2,23,4],dtype=np.int)
print(a.dtype)

int64


In [12]:
a = np.array([2,23,4],dtype=np.float32)
print(a.dtype)

float32


In [37]:
a = np.empty((3,4),dtype=float)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
a = np.linspace(1,10,12).reshape((3,4))
print(a)

[[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]


In [61]:
a = np.array([10,20,30,40])
b = np.arange(4)
c=10*np.sin(a)
print(a,b)
print(c)

[10 20 30 40] [0 1 2 3]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [64]:
print(b==3)

[False False False  True]


In [66]:
a = ([1,1],[2,2])
b = np.arange(4).reshape(2,2)
c_dot = np.dot(a,b)
print(c_dot)

[[2 4]
 [4 8]]


In [71]:
a = np.random.random((2,4))
print(a)
print(np.max(a))
print(np.sum(a))

[[0.41892271 0.06183257 0.41477285 0.00107835]
 [0.99591502 0.97996317 0.43961855 0.18382666]]
0.9959150182124288
3.4959298785766384
